Link formatting
HTTP-APIs/hydra-python-core pull request #79
Opened 2021-05-24 16:28 UTC by Mec-iS

2021-05-24 18:23 UTC, farazkhanfk7 requested changes
These changes that were made in some commits throughout HydraEntrypoint class are not compatible with develop branch of hydrus. I have tested both hydrus and core repo locally in same virtual environment and I don't think we should merge these as it will result in the failure of tests in hydrus.

@sameshl Can you please confirm ?
@Mec-iS Should we split this one big PR into multiple PRs ?

2021-05-24 18:23 UTC, farazkhanfk7 commented on hydra_python_core/doc_writer.py
> +                collection_id = uri
Some changes that were made in HydraEntrypoint class in previous commits are resulting in breakage.

2021-05-24 18:23 UTC, farazkhanfk7 commented on hydra_python_core/doc_writer.py
> +                DocUrl.doc_url, quote(collection.path, safe="")
if `collection.path` isn't available `self.name` should be used.

2021-05-24 19:04 UTC, Mec-iS commented
thanks for looking into this.
Please proceed as you see fit, I will follow.

2021-05-25 04:51 UTC, chrizandr commented
Yes these commits were to be added to core before merging #518 in hydrus. I had mentioned that in the review too. Let's merge these ASAP so hydrus builds don't fail.

2021-05-28 15:21 UTC, sameshl commented
@farazkhanfk7 Can you finish the remaining part of this PR so we merge it?

2021-05-28 15:30 UTC, farazkhanfk7 commented
Yes. I'll do it today itself. Was facing an issue in pep8 tests. I've added a question on slack related to it.

2021-05-28 16:35 UTC, Mec-iS commented
Changes applied in #81

2021-05-28 16:35 UTC, closed without merging